# Video name you wish to make inference on
# E.g., mating1, mating2, mating3, etc.
video_name: mating1

# ----------------------------------------------------------------
# BotSORT tracker
#To run botsort.py edit here.
botsort:
 adaptive_thresholding: False # if True, single_class can't be True. See below.
 single_class: True # if True, adaptive_threshold can't be True. See below.

# Note adaptive thresholding can't be done with single_class. If single class is True, adaptive_thresholding will automatically be False.

# ---------------------------------------------------------------
# DeeSORT tracker

# To run `segmentation.py` edit here.
segmentation:
 sam: False

# To run `worm_tracker.py`, edit here.
worm_tracker:
 adaptive_thresholding: True  # if True, single_class can't be True. See below.
 sam: False
 single_class: False  # if True, adaptive_threshold can't be True. See below.

# Note adaptive thresholding can't be done with single_class. If single class is True, adaptive_thresholding will automatically be False.
